services:
  - type: web
    name: chess-matchmaking
    env: python
    plan: free
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: schessis-db
          property: connectionString

databases:
  - name: schessis-db
    plan: free
    region: frankfurt
